# Generated by Django 4.2.8 on 2023-12-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_avgtime_tblcortex_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcortex',
            options={'managed': True},
        ),
    ]
