# Generated by Django 4.2.8 on 2023-12-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_tblcortex_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcortex',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
