# Generated by Django 4.2.8 on 2023-12-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_tblcortex_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='iQTabs_Tblusagedata',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, db_column='PROJECT_NAME', max_length=255, null=True)),
                ('dsc_job_number', models.CharField(blank=True, db_column='DSC_JOB_NUMBER', max_length=255, null=True)),
                ('tab_plan_type', models.CharField(blank=True, db_column='TAB_PLAN_TYPE', max_length=255, null=True)),
                ('budget_hours', models.FloatField(blank=True, db_column='BUDGET_HOURS', null=True)),
                ('execution_status', models.CharField(blank=True, db_column='EXECUTION_STATUS', max_length=255, null=True)),
                ('date_time_stamp', models.DateTimeField(blank=True, db_column='DATE_TIME_STAMP', null=True)),
                ('project_sid', models.CharField(blank=True, db_column='PROJECT_SID', max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=255, null=True)),
                ('total_warnings', models.IntegerField(blank=True, db_column='TOTAL_WARNINGS', null=True)),
                ('total_time_coding', models.FloatField(blank=True, db_column='TOTAL_TIME_CODING', null=True)),
                ('total_time_editing', models.FloatField(blank=True, db_column='TOTAL_TIME_EDITING', null=True)),
                ('region', models.CharField(blank=True, db_column='REGION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblUsageData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='iQTabs_Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(db_column='PROGRAM NAME', max_length=50)),
                ('version', models.FloatField(blank=True, db_column='VERSION', null=True)),
            ],
            options={
                'db_table': 'Version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'password',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblexecutionlogs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, db_column='PROJECT_NAME', max_length=255, null=True)),
                ('project_sid', models.CharField(blank=True, db_column='PROJECT_SID', max_length=255, null=True)),
                ('tab_plan_type', models.CharField(blank=True, db_column='TAB_PLAN_TYPE', max_length=255, null=True)),
                ('log_type', models.CharField(blank=True, db_column='LOG_TYPE', max_length=255, null=True)),
                ('log_description', models.TextField(blank=True, db_column='LOG_DESCRIPTION', null=True)),
                ('date_time_stamp', models.DateTimeField(blank=True, db_column='DATE_TIME_STAMP', null=True)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=255, null=True)),
                ('region', models.CharField(blank=True, db_column='REGION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblExecutionLogs',
                'managed': False,
            },
        ),
    ]
